### ISSUE TITLE
*** stack smashing detected ***: /usr/local/bin/mpt-receiver terminated

### ISSUE THREAD

**Issue by zkraus** [orpiske/msg-perf-tool#2]
running -p 20 -t 100 against Artemis 2.0, receiver died with *** stack smashing detected ***

if I can reproduce, I will attach backtrace

**Comment by zkraus** [comment]
Thread 1 (Thread 0x7fb3ac774780 (LWP 19234)):
#0  x86_64_fallback_frame_state (context=0x7ffd396f9aa0, context=0x7ffd396f9aa0, fs=0x7ffd396f9b90) at ./md-unwind-support.h:58
#1  uw_frame_state_for (context=context@entry=0x7ffd396f9aa0, fs=fs@entry=0x7ffd396f9b90) at /var/tmp/portage/sys-devel/gcc-4.9.4/work/gcc-4.9.4/libgcc/unwind-dw2.c:1253
#2  0x00007fb3a7b1f3c8 in _Unwind_Backtrace (trace=0x7fb3aa042790 <backtrace_helper>, trace_argument=0x7ffd396f9d50)
    at /var/tmp/portage/sys-devel/gcc-4.9.4/work/gcc-4.9.4/libgcc/unwind.inc:290
#3  0x00007fb3aa0428ff in backtrace () from /lib64/libc.so.6
#4  0x00007fb3a9f6d999 in backtrace_and_maps () from /lib64/libc.so.6
#5  0x00007fb3a9fbd383 in __libc_message () from /lib64/libc.so.6
#6  0x00007fb3aa045ee7 in __fortify_fail () from /lib64/libc.so.6
#7  0x00007fb3aa045eb0 in __stack_chk_fail () from /lib64/libc.so.6
#8  0x0000000000401ebf in main ()

**Comment by zkraus** [comment]
#0  0x00007fb300004b2c in ?? ()
#1  0x0000000000401fc8 in receiver_start ()
#2  0x0000000000401ce0 in main ()

**Comment by orpiske** [comment]
Fixed with the latest commit on master.
